# Generated by Django 4.2.4 on 2023-09-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_address_sgg_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner_complete',
            field=models.BooleanField(default=False),
        ),
    ]
