# Generated by Django 4.2.4 on 2023-09-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_owner_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_sgg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_sido',
        ),
        migrations.AddField(
            model_name='user',
            name='address_str',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
