# Generated by Django 4.2.4 on 2023-10-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='license_img',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
