# Generated by Django 4.2.4 on 2023-10-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_license_img_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='license_number',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
