# Generated by Django 4.2.4 on 2023-10-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
