# Generated by Django 4.2.4 on 2023-09-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ammount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
