# Generated by Django 4.2.4 on 2023-09-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='address_road',
            new_name='address_str',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='address_sgg',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='address_sido',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='address_sido_code',
            field=models.CharField(default=51, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='address_sgg_code',
            field=models.CharField(max_length=3),
        ),
    ]
