<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-08-17 04:22

from django.db import migrations, models
=======
# Generated by Django 4.2.4 on 2023-08-14 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> fad4d380b063c69df08126a4578a64d6e5538a9e
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> fad4d380b063c69df08126a4578a64d6e5538a9e
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> fad4d380b063c69df08126a4578a64d6e5538a9e
            name='ChatRoom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='만든날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='변경날짜')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
<<<<<<< HEAD
=======
                ('one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_member_one', to=settings.AUTH_USER_MODEL)),
                ('two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_member_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='만든날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='변경날짜')),
                ('text', models.TextField()),
                ('chat_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatroom')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
>>>>>>> fad4d380b063c69df08126a4578a64d6e5538a9e
            ],
            options={
                'abstract': False,
            },
        ),
    ]
