# Generated by Django 4.2.4 on 2023-11-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_postrecord_replyrecord_resumerecord_delete_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrecord',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replyrecord',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumerecord',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
