# Generated by Django 4.2.4 on 2023-11-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_postrecord_value_replyrecord_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrecord',
            name='value',
        ),
        migrations.RemoveField(
            model_name='replyrecord',
            name='value',
        ),
        migrations.RemoveField(
            model_name='resumerecord',
            name='value',
        ),
    ]
