# Generated by Django 4.2.4 on 2023-11-02 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0006_remove_resume_address2_sgg_code_and_more'),
        ('records', '0006_remove_postrecord_value_remove_replyrecord_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ResumeRecord',
        ),
    ]
