# Generated by Django 4.2.4 on 2023-08-17 14:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Date should be a valid 8-digit number or a day of the week.', regex='^(?:\\d{8}|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)$')])),
                ('am', models.BooleanField(default=True)),
                ('pm', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', models.ManyToManyField(to='schedules.day')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('is_recruit', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
