# Generated by Django 4.2.4 on 2023-09-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='address2_sgg_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='address2_sido_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='address_sgg_code',
            field=models.CharField(default=650, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='address_sido_code',
            field=models.CharField(default=11, max_length=2),
            preserve_default=False,
        ),
    ]
