# Generated by Django 4.2.4 on 2023-09-18 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Date should be a valid 8-digit number or a day of the week.', regex='^(?:\\d{10}|monday|tuesday|wednesday|thursday|friday|saturday|sunday)$')]),
        ),
    ]
