# Generated by Django 4.2.4 on 2023-08-09 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Date should be a valid 8-digit number or a day of the week.', regex='^(?:\\d{8}|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)$')]),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('date', 'am', 'pm')},
        ),
    ]
