# Generated by Django 4.2.4 on 2023-08-11 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_day_date_alter_day_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='schedule',
        ),
        migrations.AddField(
            model_name='recruit',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.schedule'),
        ),
        migrations.AddField(
            model_name='resume',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.schedule'),
        ),
    ]
