# Generated by Django 4.2.4 on 2023-08-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_remove_recruit_schedule_remove_resume_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_recruit',
            field=models.BooleanField(default=False),
        ),
    ]
