# Generated by Django 4.2.4 on 2023-09-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_day_date'),
        ('schedules', '0004_resume_created_at_resume_updated_at'),
    ]

    operations = [
    ]
