# Generated by Django 4.2.4 on 2023-10-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_merge_20230920_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='address2_sgg_code',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='address2_sido_code',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='address_sgg_code',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='address_sido_code',
        ),
    ]
