# Generated by Django 4.2.4 on 2023-08-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_resume_is_recruit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recruit',
        ),
    ]
