# Generated by Django 4.2.4 on 2023-11-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_resume_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='address_sgg_code',
            field=models.CharField(default=999, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='address_sido_code',
            field=models.CharField(default=99, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='address_str',
            field=models.CharField(default='asdf', max_length=20),
            preserve_default=False,
        ),
    ]
