# Generated by Django 4.2.4 on 2023-11-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_resume_address_sgg_code_resume_address_sido_code_and_more'),
        ('schedules', '0009_alter_surveyquestion_answer_choice'),
    ]

    operations = [
    ]
